#!/bin/bash

##############################################################################
# Test Event Generator for Dashboard Testing
#
# Generates realistic behavior events to test the dashboard:
# - PAGE_VIEW (visits)
# - CLICK (engagement)
# - APPROVED (FCFS success)
# - PURCHASE (conversions)
#
# Usage: ./generate-test-events.sh [activityId] [numUsers]
##############################################################################

set -e

# Configuration
ENTRY_SERVICE_URL="${ENTRY_SERVICE_URL:-http://localhost:8081}"
CORE_SERVICE_URL="${CORE_SERVICE_URL:-http://localhost:8080}"
ACTIVITY_ID="${1:-1}"
NUM_USERS="${2:-50}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📊 Generating Test Events for Dashboard"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Activity ID: $ACTIVITY_ID"
echo "Users: $NUM_USERS"
echo "Entry Service: $ENTRY_SERVICE_URL"
echo "Core Service: $CORE_SERVICE_URL"
echo ""

# Funnel conversion rates (realistic)
CLICK_RATE=0.4   # 40% of visitors click
APPROVED_RATE=0.3  # 30% of clickers get approved (FCFS)
PURCHASE_RATE=0.7  # 70% of approved complete purchase

# Calculate funnel counts
VISITORS=$NUM_USERS
CLICKERS=$(echo "$VISITORS * $CLICK_RATE" | bc | awk '{print int($1)}')
APPROVED=$(echo "$CLICKERS * $APPROVED_RATE" | bc | awk '{print int($1)}')
PURCHASES=$(echo "$APPROVED * $PURCHASE_RATE" | bc | awk '{print int($1)}')

echo "Expected Funnel:"
echo "  👁️  Visitors:  $VISITORS"
echo "  👆 Clicks:    $CLICKERS  (${CLICK_RATE}% conversion)"
echo "  ✅ Approved:  $APPROVED  (${APPROVED_RATE}% conversion)"
echo "  💰 Purchases: $PURCHASES (${PURCHASE_RATE}% conversion)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Function to send behavior event
send_event() {
    local trigger_type=$1
    local user_id=$2
    local session_id=$3

    curl -s -X POST "${ENTRY_SERVICE_URL}/api/v1/behavior/events" \
        -H "Content-Type: application/json" \
        -d @- <<EOF
{
  "eventName": "${trigger_type}_test",
  "triggerType": "${trigger_type}",
  "occurredAt": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "userId": ${user_id},
  "sessionId": "${session_id}",
  "pageUrl": "http://localhost:8080/campaign-activity/${ACTIVITY_ID}/detail",
  "referrer": "http://localhost:8080/campaigns",
  "userAgent": "TestBot/1.0",
  "properties": {
    "activityId": ${ACTIVITY_ID},
    "source": "test-script"
  }
}
EOF
}

# Generate PAGE_VIEW events (all users visit)
echo "🌐 Generating $VISITORS PAGE_VIEW events..."
for i in $(seq 1 $VISITORS); do
    USER_ID=$((1000 + i))
    SESSION_ID="test-session-${USER_ID}"
    send_event "PAGE_VIEW" $USER_ID $SESSION_ID > /dev/null
    echo -n "."
done
echo " ✅ Done"

# Generate CLICK events (40% of visitors)
echo "👆 Generating $CLICKERS CLICK events..."
for i in $(seq 1 $CLICKERS); do
    USER_ID=$((1000 + i))
    SESSION_ID="test-session-${USER_ID}"
    send_event "CLICK" $USER_ID $SESSION_ID > /dev/null
    echo -n "."
    sleep 0.1  # Small delay to avoid overwhelming server
done
echo " ✅ Done"

# Note: APPROVED and PURCHASE events are generated by backend
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ Frontend events generated successfully!"
echo ""
echo "📝 Note: APPROVED and PURCHASE events are backend-generated"
echo "   They will appear when users actually:"
echo "   - Get approved in FCFS (via Entry-service)"
echo "   - Complete payment (via Core-service)"
echo ""
echo "🔍 Verify events in Elasticsearch:"
echo "   curl http://localhost:9200/behavior-events/_count"
echo ""
echo "📊 Test dashboard at:"
echo "   curl http://localhost:8080/api/v1/dashboard/activity/${ACTIVITY_ID}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
